### PR TITLE
fix empty section under Today after midnight

### LINKED ISSUE #16: Today section is empty after midnight
After midnight (not sure about the exact time)  the section under Today is empty and  at day time (not sure about the exact time) it will show the weather.
[output.txt](https://github.com/bjesus/wttrbar/files/13034982/output.txt)

### PR DESCRIPTION
**Pull request by BluewyDiamond**
fixes #16. This is my first time doing a pull request and I'm inexperienced with rust code and coding in general. However I think I fixed it following the idea it might have been, I might be wrong.

### CODE REVIEW

**Comment by bjesus** [comment]
Thank you for submitting this! I decided to fix this in a slightly different, completely removing "yesterday" from the array before iterating over it: https://github.com/bjesus/wttrbar/commit/ecdbac4f89de670cfb95117e00c12159a58dec7d

unless you think there's still some improvement to do here, I think we can close the PR

**Comment by bjesus** [comment]
oh, `i` doesn't have anything to do with the hour. `hour["time"]` does. `i` is the index of the day, and so if `i == 0`, we're looking at the first day in array of days. the idea is to hide hours that have already passed, so for example if the time now is 12pm, we want to hide all hours before 12pm, but **only at the first day**. today at 10am shouldn't appear (`i == 0`), but tomorrow (i == 1) and the day after (`i==2`) it should.

**Comment by BluewyDiamond** [comment]
So theoretically if it is 12PM the weather report at 00AM 03AM 09AM should not be displayed that is what I understood but I don't see in the tool-tip any skipping whatsoever, in other words it is always showing all the hours.

Running wttrbar around  at 15:34 the weather report at this said hours in the tooltip  00AM 03AM 09AM 12AM is not being hidden.
[output2.txt](https://github.com/bjesus/wttrbar/files/13060804/output2.txt)

**Comment by BluewyDiamond** [comment]
https://github.com/bjesus/wttrbar/blob/3e04d0233310a17d9b1ae5ccbe2abf2eb417ae04/main.rs#L212
If I'm not wrong this if condition will always be false and will never skip because 
https://github.com/bjesus/wttrbar/blob/3e04d0233310a17d9b1ae5ccbe2abf2eb417ae04/main.rs#L214C82-L214C82
will always be false since the left side at its smallest is 0 and the right side is 2 - 2 which is 0 so 0 < 0 will always be false.

I think, I might be wrong.

**Comment by bjesus** [comment]
ah sorry about that, I committed the wrong code earlier. should be fixed now at https://github.com/bjesus/wttrbar/commit/97e99466da0e0cead5b5856d55c8950096a5201e

**Comment by BluewyDiamond** [comment]
I'm pretty sure this can still cause a underflow as in it goes under the u32 limit. For example if now.time() is 0 or 1 which corresponds to 00AM and 01AM and if we subtract 2 the compiler will throw me an error. I changed the value now.time() to 0 to simulate that it is 00AM.

Compiling wttrbar v0.5.2 (/home/bluewy/Repositories/wttrbar-git)
error: this arithmetic operation will overflow
   --> main.rs:222:66
    |
222 |                 && formatted_hour_time.parse::<u32>().unwrap() < 0 - 2
    |                                                                  ^^^^^ attempt to compute `0_u32 - 2_u32`, which would overflow
    |
    = note: `#[deny(arithmetic_overflow)]` on by default

error: could not compile `wttrbar` (bin "wttrbar") due to previous error

**Comment by BluewyDiamond** [comment]
btw while we are at it, can we add a vertical format option for the output? Since I use waybar vertically what I did is add a \n at the line https://github.com/bjesus/wttrbar/blob/97e99466da0e0cead5b5856d55c8950096a5201e/main.rs#L140 so it looks somethig like this "{}\n{}". 

Something like a flag which triggers it will do.

**Pull request closed without merging**
