### PR TITLE
New featues

### PR DESCRIPTION
**Pull request by dianaw353**
This is built on top of nut-3 fork.
Current new features on top of nut-3 changes:
- reactored code
- switch icons to use nerd font icons
- icons change to daytime or night version depending on time of day

### CODE REVIEW

**Comment by bjesus** [comment]
Thanks @dianaw353 ! What's the benefit of having the process always running vs spawning it every 30 minutes? I feel like if it's always running there will always be the risk of introducing some memory leak

**Comment by bjesus** [comment]
sorry I just realized that the "always on" process is more due to the fact this is based on #23 so I posted the question there.

curious - why do you prefer nerd fonts? I always felt it's a little hacky, and well, black and white. also, what does "icons change to daytime or night version depending on time of day"? can you share a screenshot? I tried looking up the icon IDs here: https://www.nerdfonts.com/cheat-sheet but it couldn't really understand what is day version and what is night version.

**Comment by dianaw353** [comment]
I am still working on trying to get the icons to switch between daytime and night time icons as it dosent work properly yet... I pefer to use the nerdfont icons as it is more clean and we can can change the color of them depending if it is sunney, rainy,snow etc. The daytime icons are the icons with a moon icon insead of a sunny icon

**Comment by bjesus** [comment]
okay, I see. I don't think I will want to change the font to nerd font, definitely not as a default thing. I can consider merging this if this was an optional thing. I do like the idea of moon/sun based icons though, that's cool!

**Comment by dianaw353** [comment]
closing as #27 my try 2 at adding nerd font flag

**Pull request closed without merging**
